modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "https://github.com/Yedelo/Fontrast/issues"

[[mods]]
modId = "fontrast"
version = "${version}"
displayName = "Fontrast"
description = "Adds numerous ways to customize the look of text"
logoFile = "assets/fontrast/logo/fontrast.png"
logoBlur = false
authors = "Yedel"
displayURL = "https://modrinth.com/mod/fontrast/"

[[mixins]]
config = "fontrast.mixins.json5"

[features.fontrast]
javaVersion = "${java}"

[[dependencies.fontrast]]
modId = "neoforge"
versionRange = "${neoforge}"

[[dependencies.fontrast]]
modId = "minecraft"
versionRange = "${minecraft}"

[[dependencies.fontrast]]
modId = "yet_another_config_lib_v3"
versionRange = "${yacl}"
